# Funding options for Yolo Deep-Ag Copilot (AgriBot)
# Support the development of open-source agricultural intelligence tools

# GitHub Sponsors (Recommended for open source projects)
github: [himanshu-nimonkar]
